// <auto-generated />
namespace Tool_World.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CorrectMemTypeOnCustMdl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorrectMemTypeOnCustMdl));
        
        string IMigrationMetadata.Id
        {
            get { return "202010201819328_CorrectMemTypeOnCustMdl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
